### PR TITLE
updates langchain version to allow >=0.0.0 <1.0.0

### PR DESCRIPTION
**Pull request by aliyeysides**
This PR updates langchain version to >=0.0.0 <1.0.0

All tests are passing.

Should resolve:
```
Because no versions of yolopandas match >0.0.3,<0.0.4
 and yolopandas (0.0.3) depends on langchain (>=0.0.60,<0.0.61), yolopandas (>=0.0.3,<0.0.4) requires langchain (>=0.0.60,<0.0.61).
```

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
langchain = "^0"

probably better so it doesnt get out of date

**Comment by aliyeysides** [comment]
@hwchase17 agree, done 👍🏽

**Comment by aliyeysides** [comment]
Closing since @ccurme updated.

**Comment by ccurme** [comment]
@aliyeysides Apologies, saw this PR too late!

**Pull request closed without merging**
